### PR TITLE
fix(Emails): remove subject from arguments

### LINKED ISSUE #82: Emails service - make subject optional

### PR DESCRIPTION
**Pull request by mapra99**
Closes #82
Emails subject is currently being set from here and sent to SendGrid. This should be the responsibility of the SendGrid template and not from this backend, so this PR removes this argument from the service classes, the model and the table in the db

### CODE REVIEW

File: db/migrate/20220812053938_remove_subject_from_email_communications.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+class RemoveSubjectFromEmailCommunications < ActiveRecord::Migration[6.1]
+  def up
+    remove_column :email_communications, :subject
+  end
+
+  def down
+    add_column :email_communications, :subject, :string, null: false
+  end
```
Comment (ImMPrada) [inline db/migrate/20220812053938_remove_subject_from_email_communications.rb:8]: why don't just use

```
def change
  remove_column : email_communications, : subject
end
```

**Review by ImMPrada — APPROVED** [review]
🚀

So each email will have its subject in sendgrid's template

File: db/migrate/20220812053938_remove_subject_from_email_communications.rb (hunk 1 above)
Comment (mapra99) [reply db/migrate/20220812053938_remove_subject_from_email_communications.rb:8]: A migration has to be compatible in two directions: 1) when you do `db:migrate` and 2) when you want to `db:rollback`. When you use the `change` method, all the changes you want to make inside the method must be reversible changes, so for example if you do `create_table`, rails is smart enough to assume that the reverse operation is `remove_table`.

When rails is not smart enough, or when you need to do something very custom, you can be explicit on what needs to be done on `db:migrate` (the `up` method), and what needs to be done on `db:rollback` (the `down` method). 
https://guides.rubyonrails.org/active_record_migrations.html#using-the-up-down-methods

This was one of these cases. Rails doesn't know what to do when you want to reverse a `remove_column` operation, so I had to be explicit and say that the reverse operation that I want is to create the column that was removed

**Comment by mapra99** [comment]
> So each email will have its subject in sendgrid's template

Yes, exactly

File: db/migrate/20220812053938_remove_subject_from_email_communications.rb (hunk 1 above)
Comment (ImMPrada) [reply db/migrate/20220812053938_remove_subject_from_email_communications.rb:8]: So interesting!
